/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import java.io.IOException;
import metier.Fichier;
import metier.Graphe;

/**
 *
 * @author ASUS
 */
public class Grama extends javax.swing.JFrame {

    private Graphe graphe;
    /**
     * Creates new form GRAMA
     */
    public Grama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        ecrantPrincipal = new javax.swing.JDialog();
        listeMethode = new javax.swing.JComboBox<>();
        jExecuter = new javax.swing.JButton();
        detailGraphe = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jInfoFichier = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jOuvrir = new javax.swing.JMenuItem();

        listeMethode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "information sur le graphe", "voisin à un saut", "voisin à 2 saut", "comparaison entre 2 sommets", " " }));

        jExecuter.setText("Executer");
        jExecuter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecuterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ecrantPrincipalLayout = new javax.swing.GroupLayout(ecrantPrincipal.getContentPane());
        ecrantPrincipal.getContentPane().setLayout(ecrantPrincipalLayout);
        ecrantPrincipalLayout.setHorizontalGroup(
            ecrantPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ecrantPrincipalLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(listeMethode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jExecuter)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        ecrantPrincipalLayout.setVerticalGroup(
            ecrantPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ecrantPrincipalLayout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addGroup(ecrantPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeMethode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExecuter))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout detailGrapheLayout = new javax.swing.GroupLayout(detailGraphe.getContentPane());
        detailGraphe.getContentPane().setLayout(detailGrapheLayout);
        detailGrapheLayout.setHorizontalGroup(
            detailGrapheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        detailGrapheLayout.setVerticalGroup(
            detailGrapheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grama");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenue de GRAMA");

        jInfoFichier.setText("Veuillez ouvrir le fichier contenant les sommets du graphe");

        jMenu.setText("Menu");

        jOuvrir.setText("Ouvrir");
        jOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOuvrirActionPerformed(evt);
            }
        });
        jMenu.add(jOuvrir);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jInfoFichier))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(jInfoFichier)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOuvrirActionPerformed
        // TODO add your handling code here:
        jFileChooser.showOpenDialog(this);
        try {
            graphe = new Graphe(Fichier.DécoupageFichier(jFileChooser.getSelectedFile().getName()));
            jInfoFichier.setText("Fichier "+jFileChooser.getSelectedFile().getName()+" chargé");
        } catch (IOException ex) {
            jInfoFichier.setText("Aucun fichier trouvé");
        }
        ecrantPrincipal.setVisible(true);
        ecrantPrincipal.pack();
        /*DrawGraphic g = new DrawGraphic(graphe);
        ecrantPrincipal.add(g);
        g.setSize(500, 500);*/
    }//GEN-LAST:event_jOuvrirActionPerformed

    private void jExecuterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExecuterActionPerformed
        // TODO add your handling code here:
        if(((String)listeMethode.getSelectedItem()).equals("information sur le graphe")){
            detailGraphe.setVisible(true);
            detailGraphe.pack();
        }
        else if(((String)listeMethode.getSelectedItem()).equals("voisin à un saut")){
        
        }
        else if(((String)listeMethode.getSelectedItem()).equals("voisin à 2 saut")){
           
        }
        else if(((String)listeMethode.getSelectedItem()).equals("comparaison entre 2 sommets")){
            
        }
        ecrantPrincipal.setVisible(false);
    }//GEN-LAST:event_jExecuterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog detailGraphe;
    private javax.swing.JDialog ecrantPrincipal;
    private javax.swing.JButton jExecuter;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jInfoFichier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jOuvrir;
    private javax.swing.JComboBox<String> listeMethode;
    // End of variables declaration//GEN-END:variables
}
